const express = require("express")
const router = express.Router()
const authRoutes = require("./auth/auth.routes")
const resumeManagementRoutes = require("./resumeManagement/resume.routes")
const portfolioResumeRoutes = require("./portfolioResume/portfolioResume.routes")
const IndustryCategoryRoutes = require("./industry/industry.routes")
const CategoryRoutes = require("./category/category.routes")
const toolRoutes = require("./tool/tool.routes")
const skillRoutes = require("./skill/skill.routes")
const portfolioRoutes = require("./portfolio/portfolio.routes")
const companyRoutes = require("./company/company.routes")
const dashboardRoutes = require("./dashboard/dashboard.routes")

router.use("/auth", authRoutes)
router.use("/resume", resumeManagementRoutes)
router.use("/portfolio-resume", portfolioResumeRoutes)
router.use("/industry", IndustryCategoryRoutes)
router.use("/category", CategoryRoutes)
router.use("/tool", toolRoutes)
router.use("/skill", skillRoutes)
router.use("/portfolio", portfolioRoutes)
router.use("/company", companyRoutes)
router.use("/dashboard", dashboardRoutes)

module.exports = router
